model_list:
  - model_name: gpt-5
    litellm_params:
      model: openai/gpt-5
      reasoning_effort: os.environ/REASONING_EFFORT

  - model_name: gpt-5-mini
    litellm_params:
      model: openai/gpt-5-mini
      reasoning_effort: os.environ/REASONING_EFFORT

  - model_name: claude-3-5-haiku-20241022
    litellm_params:
      model: anthropic/claude-3-5-haiku-20241022

  - model_name: claude-sonnet-4-20250514
    litellm_params:
      model: anthropic/claude-sonnet-4-20250514

  - model_name: claude-opus-4-1-20250805
    litellm_params:
      model: anthropic/claude-opus-4-1-20250805
