model_list:
  - model_name: claude-sonnet-4-20250514
    litellm_params:
      model: openai/gpt-5
      api_key: os.environ/OPENAI_API_KEY
      reasoning_effort: os.environ/REASONING_EFFORT

  - model_name: claude-3-5-haiku-20241022
    litellm_params:
      model: anthropic/claude-3-5-haiku-20241022
      api_key: os.environ/ANTHROPIC_API_KEY
